# Generated by Django 4.2.11 on 2024-04-15 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0003_rename_date_accepted_order_date_planned_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date_planned",
        ),
        migrations.AlterField(
            model_name="order",
            name="date_ready",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
