# Generated by Django 4.2.11 on 2024-04-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0004_remove_order_date_planned_alter_order_date_ready"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=17, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("client", "Client"), ("worker", "Worker")],
                default="client",
                max_length=50,
            ),
        ),
    ]
