# Generated by Django 4.2.11 on 2024-04-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0005_alter_client_phone_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=256, verbose_name="Phone Number"),
        ),
    ]
