# Generated by Django 4.2.11 on 2024-04-19 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0006_alter_client_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_description",
        ),
        migrations.AddField(
            model_name="order",
            name="date_accept",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_ready",
            field=models.DateTimeField(),
        ),
    ]
