# Generated by Django 4.2.11 on 2024-04-19 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0007_remove_order_order_description_order_date_accept_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_accept",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
