# Generated by Django 4.2.11 on 2024-04-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0008_alter_order_date_accept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_ready",
            field=models.DateTimeField(null=True),
        ),
    ]
