# Generated by Django 4.2.11 on 2024-04-19 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0009_alter_order_date_ready"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_accept",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.CharField(max_length=256, null=True, verbose_name="Notes"),
        ),
    ]
