# Generated by Django 4.2.11 on 2024-05-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0010_alter_order_date_accept_alter_order_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Client Notes"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_accept",
            field=models.DateTimeField(null=True),
        ),
    ]
