# Generated by Django 4.2.11 on 2024-05-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0011_client_notes_alter_order_date_accept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_accept",
            field=models.DateField(null=True),
        ),
    ]
