# Generated by Django 4.2.11 on 2024-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0012_alter_order_date_accept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_accept",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_ready",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Notes"
            ),
        ),
    ]
