# Generated by Django 4.2.11 on 2024-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0013_alter_order_date_accept_alter_order_date_ready_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_urgent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
