# Generated by Django 4.2.11 on 2024-05-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0015_worker_balance_worker_hire_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Owner",
        ),
    ]
