# Generated by Django 4.2.11 on 2024-05-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0016_delete_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="CRM.worker",
            ),
        ),
    ]
