# Generated by Django 4.2.11 on 2024-05-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0017_order_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("Запланирован", "PLANNED"),
                    ("В работе", "IN_PROGRESS"),
                    ("Сделан", "COMPLETED"),
                    ("Оплачен", "PAID"),
                    ("Оплачен, но не сделан", "PAID_BUT_NOT_COMPLETED"),
                    ("Сделан, но неоплачен", "COMPLETED_BUT_NOT_PAID"),
                    ("Клиент забрал заказ", "TAKEN"),
                ],
                default="Запланирован",
                max_length=21,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("worker", "Worker"),
                    ("owner", "Owner"),
                ],
                default="client",
                max_length=50,
            ),
        ),
    ]
