# Generated by Django 4.2.11 on 2024-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0018_alter_order_state_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_notified",
            field=models.BooleanField(default=False),
        ),
    ]
