# Generated by Django 4.2.11 on 2024-05-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0020_businessanalytics_remove_workerhistory_order_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BusinessAnalytics",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="balance",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("guest", "Guest"), ("worker", "Worker"), ("owner", "Owner")],
                default="guest",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="WorkerStatistics",
        ),
    ]
